name: wp-automator
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmpdec=4.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.14.2
  - python_abi=3.14
  - readline=8.3
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - basedpyright==1.36.1
      - bcrypt==5.0.0
      - cffi==2.0.0
      - cryptography==46.0.3
      - invoke==2.2.1
      - nodejs-wheel-binaries==24.12.0
      - paramiko==4.0.0
      - pycparser==2.23
      - pynacl==1.6.1
      - ruff==0.14.9
      - uv==0.9.18
